version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "auto-merge"
    commit-message:
      prefix: "chore"
      include: "scope"

  # Maintain dependencies for Gradle
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "auto-merge"
    commit-message:
      prefix: "chore"
      include: "scope"
    ignore:
      # Ignore major version updates for Android Gradle Plugin
      - dependency-name: "com.android.tools.build:gradle"
        update-types: ["version-update:semver-major"]
