name: Auto-assign and Fix PR Issues
on:
  pull_request:
  pull_request:
    types: [opened, synchronize]

permissions:
  issues: write
  pull-requests: write
    types: [opened, synchronize]

jobs:
jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
    - name: Auto-assign PR
      uses: actions/github-script@v7
      with:
        script: |
          const { owner, repo, number } = context.issue;
          await github.rest.issues.addAssignees({
            owner,
            repo,
            issue_number: number,
            assignees: [context.payload.pull_request.user.login]
          });

  auto-fix:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.body, 'auto-fix')
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        ref: ${{ github.head_ref }}
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Auto-fix code style
      run: |
        ./gradlew ktlintFormat || true
        ./gradlew spotlessApply || true
    - name: Commit fixes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git diff --staged --quiet || git commit -m "Auto-fix code style and formatting"
        git push

  dependency-update:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.title, 'Update dependencies')
    steps:
    - uses: actions/checkout@v4
    - name: Auto-approve dependency updates
      uses: actions/github-script@v7
      with:
        script: |
          const { owner, repo, number } = context.issue;
          await github.rest.pulls.createReview({
            owner,
            repo,
            pull_number: number,
            event: 'APPROVE',
            body: 'Auto-approving dependency update'
          });
