name: Auto Merge PRs

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
  check_suite:
    types:
      - completed
  status: {}
  workflow_run:
    workflows: ["Android CI"]
    types:
      - completed

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: >
      (github.actor == 'dependabot[bot]' || contains(github.event.pull_request.labels.*.name, 'auto-merge')) &&
      github.event.pull_request.draft == false
    steps:
      - name: Get PR information
        id: pr-info
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            let pr_number;

            if (context.payload.pull_request) {
              pr_number = context.payload.pull_request.number;
            } else if (context.payload.workflow_run) {
              // For workflow_run events, we need to find the associated PR
              const run_id = context.payload.workflow_run.id;
              const prs = await github.rest.pulls.list({
                owner,
                repo,
                state: 'open'
              });

              for (const pr of prs.data) {
                const { data: checks } = await github.rest.checks.listForRef({
                  owner,
                  repo,
                  ref: pr.head.ref
                });

                if (checks.some(check => check.id === run_id)) {
                  pr_number = pr.number;
                  break;
                }
              }
            }

            if (!pr_number) {
              console.log('No PR found for this event');
              return;
            }

            console.log(`Processing PR #${pr_number}`);
            core.setOutput('pr_number', pr_number);

            // Check if all required checks have passed
            const { data: checks } = await github.rest.checks.listForRef({
              owner,
              repo,
              ref: context.payload.pull_request?.head.ref || context.payload.workflow_run?.head_branch
            });

            const allChecksPass = checks.every(check => check.conclusion === 'success');
            console.log(`All checks pass: ${allChecksPass}`);
            core.setOutput('all_checks_pass', allChecksPass);

      - name: Auto-merge PRs
        if: steps.pr-info.outputs.all_checks_pass == 'true'
        uses: pascalgn/automerge-action@v0.16.4
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "auto-merge,dependencies,!work in progress,!do not merge"
          MERGE_METHOD: "squash"
          MERGE_COMMIT_MESSAGE: "pull-request-title"
          MERGE_RETRIES: "6"
          MERGE_RETRY_SLEEP: "10000"
          UPDATE_LABELS: "auto-merge,dependencies"
          UPDATE_METHOD: "merge"
          MERGE_FILTER_AUTHOR: "dependabot[bot]"
          LOG: "DEBUG"
