name: Self-Updating Workflows

on:
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sunday at midnight
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-workflows:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install -g @octokit/rest yaml

      - name: Check and update workflows
        id: check-updates
        run: |
          # Define the current versions of actions used
          CHECKOUT_VERSION="v4"
          SETUP_JAVA_VERSION="v4"
          UPLOAD_ARTIFACT_VERSION="v4"
          NODE_VERSION="v4"
          GRADLE_BUILD_ACTION_VERSION="v3"
          GITHUB_SCRIPT_VERSION="v7"
          CREATE_PR_VERSION="v7"
          ANDROID_EMULATOR_RUNNER_VERSION="v2"
          AUTOMERGE_ACTION_VERSION="v0.16.4"
          AUTO_ASSIGN_ISSUE_VERSION="v1"

          # Check for newer versions
          LATEST_CHECKOUT=$(curl -s https://api.github.com/repos/actions/checkout/releases/latest | grep -Po '"tag_name": "v\K[^"]*')
          LATEST_SETUP_JAVA=$(curl -s https://api.github.com/repos/actions/setup-java/releases/latest | grep -Po '"tag_name": "v\K[^"]*')
          LATEST_UPLOAD_ARTIFACT=$(curl -s https://api.github.com/repos/actions/upload-artifact/releases/latest | grep -Po '"tag_name": "v\K[^"]*')
          LATEST_NODE=$(curl -s https://api.github.com/repos/actions/setup-node/releases/latest | grep -Po '"tag_name": "v\K[^"]*')
          LATEST_GRADLE_BUILD_ACTION=$(curl -s https://api.github.com/repos/gradle/gradle-build-action/releases/latest | grep -Po '"tag_name": "v\K[^"]*')
          LATEST_GITHUB_SCRIPT=$(curl -s https://api.github.com/repos/actions/github-script/releases/latest | grep -Po '"tag_name": "v\K[^"]*')
          LATEST_CREATE_PR=$(curl -s https://api.github.com/repos/peter-evans/create-pull-request/releases/latest | grep -Po '"tag_name": "v\K[^"]*')
          LATEST_ANDROID_EMULATOR_RUNNER=$(curl -s https://api.github.com/repos/ReactiveCircus/android-emulator-runner/releases/latest | grep -Po '"tag_name": "v\K[^"]*')
          LATEST_AUTOMERGE_ACTION=$(curl -s https://api.github.com/repos/pascalgn/automerge-action/releases/latest | grep -Po '"tag_name": "v\K[^"]*' || echo "0.16.4")
          LATEST_AUTO_ASSIGN_ISSUE=$(curl -s https://api.github.com/repos/pozil/auto-assign-issue/releases/latest | grep -Po '"tag_name": "v\K[^"]*' || echo "1")

          # Function to update workflow file
          update_workflow() {
            local file=$1
            local current_version=$2
            local latest_version=$3
            local action_name=$4

            if [[ -f $file && "$current_version" != "v$latest_version" ]]; then
              echo "Updating $action_name in $file from $current_version to v$latest_version"
              sed -i "s|uses: $action_name@$current_version|uses: $action_name@v$latest_version|g" $file
              echo "updated=true" >> $GITHUB_OUTPUT
            fi
          }

          # Update all workflow files
          for workflow in .github/workflows/*.yml; do
            update_workflow "$workflow" "$CHECKOUT_VERSION" "$LATEST_CHECKOUT" "actions/checkout"
            update_workflow "$workflow" "$SETUP_JAVA_VERSION" "$LATEST_SETUP_JAVA" "actions/setup-java"
            update_workflow "$workflow" "$UPLOAD_ARTIFACT_VERSION" "$LATEST_UPLOAD_ARTIFACT" "actions/upload-artifact"
            update_workflow "$workflow" "$NODE_VERSION" "$LATEST_NODE" "actions/setup-node"
            update_workflow "$workflow" "$GRADLE_BUILD_ACTION_VERSION" "$LATEST_GRADLE_BUILD_ACTION" "gradle/gradle-build-action"
            update_workflow "$workflow" "$GITHUB_SCRIPT_VERSION" "$LATEST_GITHUB_SCRIPT" "actions/github-script"
            update_workflow "$workflow" "$CREATE_PR_VERSION" "$LATEST_CREATE_PR" "peter-evans/create-pull-request"
            update_workflow "$workflow" "$ANDROID_EMULATOR_RUNNER_VERSION" "$LATEST_ANDROID_EMULATOR_RUNNER" "reactivecircus/android-emulator-runner"
            update_workflow "$workflow" "$AUTOMERGE_ACTION_VERSION" "$LATEST_AUTOMERGE_ACTION" "pascalgn/automerge-action"
            update_workflow "$workflow" "$AUTO_ASSIGN_ISSUE_VERSION" "$LATEST_AUTO_ASSIGN_ISSUE" "pozil/auto-assign-issue"
          done

          # Check if any updates were made
          if [[ $(git status --porcelain) ]]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        if: steps.check-updates.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update GitHub Actions to latest versions"
          title: "Auto-update GitHub Actions to latest versions"
          body: |
            This PR automatically updates the GitHub Actions used in workflows to their latest versions.

            Changes:
            - Updates actions/checkout
            - Updates actions/setup-java
            - Updates actions/upload-artifact
            - Updates actions/setup-node
            - Updates gradle/gradle-build-action
            - Updates actions/github-script
            - Updates peter-evans/create-pull-request
            - Updates reactivecircus/android-emulator-runner
            - Updates pascalgn/automerge-action
            - Updates pozil/auto-assign-issue

            This PR was created automatically by the self-updating workflow system.
          branch: auto-update-actions
          base: main
          labels: auto-merge,dependencies
